### ISSUE TITLE
Exported model's head does not scale when speaking

### ISSUE THREAD

**Issue by Artorp** [MozillaReality/hubs-avatar-pipelines#5]
Exporting to glTF from the provided `AvatarBot_base_for_export.blend` gives a model that does not scale the head when you speak in Mozilla Hubs. `AvatarBot_Base.glb` in the "Exported GLB models" folder has the same issue.

Exporting two objects from Blender makes Mozilla Hubs guess (I assume) at which model is the body and which is the head and does give a setup where the "head" scales. So it's not clear why the setup in this repo does not work.

I'm on Blender 2.82.

**Comment by misslivirose** [comment]
Hey Artorp, you have to enable the animations. We're working on making this flow a little easier, perhaps with a blender plugin, but there is a flow that has to be done manually for this to work: https://github.com/MozillaReality/hubs-avatar-pipelines/wiki/Supporting-Hubs-Default-Avatar-Animations

**Comment by Artorp** [comment]
I see, missed that detail, thank you.
